// Generated by JavaScript APG, Version [`apg-js2`](https://github.com/ldthomas/apg-js2)
module.exports = function () {
  "use strict";
  //```
  // SUMMARY
  //      rules = 60
  //       udts = 0
  //    opcodes = 422
  //        ---   ABNF original opcodes
  //        ALT = 36
  //        CAT = 66
  //        REP = 53
  //        RNM = 150
  //        TLS = 76
  //        TBS = 25
  //        TRG = 16
  //        ---   SABNF superset opcodes
  //        UDT = 0
  //        AND = 0
  //        NOT = 0
  //        BKA = 0
  //        BKN = 0
  //        BKR = 0
  //        ABG = 0
  //        AEN = 0
  // characters = [9 - 1114111]
  //```
  /* OBJECT IDENTIFIER (for internal parser use) */
  this.grammarObject = "grammarObject";

  /* RULES */
  this.rules = [];
  this.rules[0] = { name: "seq", lower: "seq", index: 0, isBkr: false };
  this.rules[1] = {
    name: "one-item",
    lower: "one-item",
    index: 1,
    isBkr: false,
  };
  this.rules[2] = { name: "item", lower: "item", index: 2, isBkr: false };
  this.rules[3] = { name: "string1", lower: "string1", index: 3, isBkr: false };
  this.rules[4] = {
    name: "string1e",
    lower: "string1e",
    index: 4,
    isBkr: false,
  };
  this.rules[5] = {
    name: "ellipsis",
    lower: "ellipsis",
    index: 5,
    isBkr: false,
  };
  this.rules[6] = { name: "string", lower: "string", index: 6, isBkr: false };
  this.rules[7] = { name: "number", lower: "number", index: 7, isBkr: false };
  this.rules[8] = { name: "sign", lower: "sign", index: 8, isBkr: false };
  this.rules[9] = {
    name: "decnumber",
    lower: "decnumber",
    index: 9,
    isBkr: false,
  };
  this.rules[10] = {
    name: "hexfloat",
    lower: "hexfloat",
    index: 10,
    isBkr: false,
  };
  this.rules[11] = { name: "hexint", lower: "hexint", index: 11, isBkr: false };
  this.rules[12] = { name: "octint", lower: "octint", index: 12, isBkr: false };
  this.rules[13] = { name: "binint", lower: "binint", index: 13, isBkr: false };
  this.rules[14] = { name: "nonfin", lower: "nonfin", index: 14, isBkr: false };
  this.rules[15] = { name: "simple", lower: "simple", index: 15, isBkr: false };
  this.rules[16] = { name: "uint", lower: "uint", index: 16, isBkr: false };
  this.rules[17] = { name: "tagged", lower: "tagged", index: 17, isBkr: false };
  this.rules[18] = {
    name: "app-prefix",
    lower: "app-prefix",
    index: 18,
    isBkr: false,
  };
  this.rules[19] = {
    name: "app-string",
    lower: "app-string",
    index: 19,
    isBkr: false,
  };
  this.rules[20] = { name: "sqstr", lower: "sqstr", index: 20, isBkr: false };
  this.rules[21] = { name: "bstr", lower: "bstr", index: 21, isBkr: false };
  this.rules[22] = { name: "tstr", lower: "tstr", index: 22, isBkr: false };
  this.rules[23] = {
    name: "embedded",
    lower: "embedded",
    index: 23,
    isBkr: false,
  };
  this.rules[24] = { name: "array", lower: "array", index: 24, isBkr: false };
  this.rules[25] = { name: "map", lower: "map", index: 25, isBkr: false };
  this.rules[26] = { name: "keyp", lower: "keyp", index: 26, isBkr: false };
  this.rules[27] = { name: "blank", lower: "blank", index: 27, isBkr: false };
  this.rules[28] = {
    name: "non-slash",
    lower: "non-slash",
    index: 28,
    isBkr: false,
  };
  this.rules[29] = { name: "non-lf", lower: "non-lf", index: 29, isBkr: false };
  this.rules[30] = {
    name: "comment",
    lower: "comment",
    index: 30,
    isBkr: false,
  };
  this.rules[31] = { name: "S", lower: "s", index: 31, isBkr: false };
  this.rules[32] = { name: "MS", lower: "ms", index: 32, isBkr: false };
  this.rules[33] = { name: "MSC", lower: "msc", index: 33, isBkr: false };
  this.rules[34] = { name: "SOC", lower: "soc", index: 34, isBkr: false };
  this.rules[35] = {
    name: "streamstring",
    lower: "streamstring",
    index: 35,
    isBkr: false,
  };
  this.rules[36] = { name: "spec", lower: "spec", index: 36, isBkr: false };
  this.rules[37] = { name: "specms", lower: "specms", index: 37, isBkr: false };
  this.rules[38] = {
    name: "double-quoted",
    lower: "double-quoted",
    index: 38,
    isBkr: false,
  };
  this.rules[39] = {
    name: "single-quoted",
    lower: "single-quoted",
    index: 39,
    isBkr: false,
  };
  this.rules[40] = {
    name: "escapable",
    lower: "escapable",
    index: 40,
    isBkr: false,
  };
  this.rules[41] = {
    name: "hexchar",
    lower: "hexchar",
    index: 41,
    isBkr: false,
  };
  this.rules[42] = {
    name: "non-surrogate",
    lower: "non-surrogate",
    index: 42,
    isBkr: false,
  };
  this.rules[43] = {
    name: "high-surrogate",
    lower: "high-surrogate",
    index: 43,
    isBkr: false,
  };
  this.rules[44] = {
    name: "low-surrogate",
    lower: "low-surrogate",
    index: 44,
    isBkr: false,
  };
  this.rules[45] = {
    name: "hexscalar",
    lower: "hexscalar",
    index: 45,
    isBkr: false,
  };
  this.rules[46] = {
    name: "unescaped",
    lower: "unescaped",
    index: 46,
    isBkr: false,
  };
  this.rules[47] = { name: "DQUOTE", lower: "dquote", index: 47, isBkr: false };
  this.rules[48] = { name: "SQUOTE", lower: "squote", index: 48, isBkr: false };
  this.rules[49] = { name: "DIGIT", lower: "digit", index: 49, isBkr: false };
  this.rules[50] = { name: "DIGIT1", lower: "digit1", index: 50, isBkr: false };
  this.rules[51] = { name: "ODIGIT", lower: "odigit", index: 51, isBkr: false };
  this.rules[52] = { name: "BDIGIT", lower: "bdigit", index: 52, isBkr: false };
  this.rules[53] = { name: "HEXDIG", lower: "hexdig", index: 53, isBkr: false };
  this.rules[54] = {
    name: "HEXDIG1",
    lower: "hexdig1",
    index: 54,
    isBkr: false,
  };
  this.rules[55] = {
    name: "lcalpha",
    lower: "lcalpha",
    index: 55,
    isBkr: false,
  };
  this.rules[56] = {
    name: "lcalnum",
    lower: "lcalnum",
    index: 56,
    isBkr: false,
  };
  this.rules[57] = {
    name: "ucalpha",
    lower: "ucalpha",
    index: 57,
    isBkr: false,
  };
  this.rules[58] = {
    name: "ucalnum",
    lower: "ucalnum",
    index: 58,
    isBkr: false,
  };
  this.rules[59] = {
    name: "wordchar",
    lower: "wordchar",
    index: 59,
    isBkr: false,
  };

  /* UDTS */
  this.udts = [];

  /* OPCODES */
  /* seq */
  this.rules[0].opcodes = [];
  this.rules[0].opcodes[0] = { type: 2, children: [1, 2] }; // CAT
  this.rules[0].opcodes[1] = { type: 4, index: 31 }; // RNM(S)
  this.rules[0].opcodes[2] = { type: 3, min: 0, max: 1 }; // REP
  this.rules[0].opcodes[3] = { type: 2, children: [4, 5, 9] }; // CAT
  this.rules[0].opcodes[4] = { type: 4, index: 2 }; // RNM(item)
  this.rules[0].opcodes[5] = { type: 3, min: 0, max: Infinity }; // REP
  this.rules[0].opcodes[6] = { type: 2, children: [7, 8] }; // CAT
  this.rules[0].opcodes[7] = { type: 4, index: 33 }; // RNM(MSC)
  this.rules[0].opcodes[8] = { type: 4, index: 2 }; // RNM(item)
  this.rules[0].opcodes[9] = { type: 4, index: 34 }; // RNM(SOC)

  /* one-item */
  this.rules[1].opcodes = [];
  this.rules[1].opcodes[0] = { type: 2, children: [1, 2, 3] }; // CAT
  this.rules[1].opcodes[1] = { type: 4, index: 31 }; // RNM(S)
  this.rules[1].opcodes[2] = { type: 4, index: 2 }; // RNM(item)
  this.rules[1].opcodes[3] = { type: 4, index: 31 }; // RNM(S)

  /* item */
  this.rules[2].opcodes = [];
  this.rules[2].opcodes[0] = { type: 1, children: [1, 2, 3, 4, 5, 6, 7] }; // ALT
  this.rules[2].opcodes[1] = { type: 4, index: 25 }; // RNM(map)
  this.rules[2].opcodes[2] = { type: 4, index: 24 }; // RNM(array)
  this.rules[2].opcodes[3] = { type: 4, index: 17 }; // RNM(tagged)
  this.rules[2].opcodes[4] = { type: 4, index: 7 }; // RNM(number)
  this.rules[2].opcodes[5] = { type: 4, index: 15 }; // RNM(simple)
  this.rules[2].opcodes[6] = { type: 4, index: 6 }; // RNM(string)
  this.rules[2].opcodes[7] = { type: 4, index: 35 }; // RNM(streamstring)

  /* string1 */
  this.rules[3].opcodes = [];
  this.rules[3].opcodes[0] = { type: 2, children: [1, 4] }; // CAT
  this.rules[3].opcodes[1] = { type: 1, children: [2, 3] }; // ALT
  this.rules[3].opcodes[2] = { type: 4, index: 22 }; // RNM(tstr)
  this.rules[3].opcodes[3] = { type: 4, index: 21 }; // RNM(bstr)
  this.rules[3].opcodes[4] = { type: 4, index: 36 }; // RNM(spec)

  /* string1e */
  this.rules[4].opcodes = [];
  this.rules[4].opcodes[0] = { type: 1, children: [1, 2] }; // ALT
  this.rules[4].opcodes[1] = { type: 4, index: 3 }; // RNM(string1)
  this.rules[4].opcodes[2] = { type: 4, index: 5 }; // RNM(ellipsis)

  /* ellipsis */
  this.rules[5].opcodes = [];
  this.rules[5].opcodes[0] = { type: 3, min: 3, max: Infinity }; // REP
  this.rules[5].opcodes[1] = { type: 7, string: [46] }; // TLS

  /* string */
  this.rules[6].opcodes = [];
  this.rules[6].opcodes[0] = { type: 2, children: [1, 2] }; // CAT
  this.rules[6].opcodes[1] = { type: 4, index: 4 }; // RNM(string1e)
  this.rules[6].opcodes[2] = { type: 3, min: 0, max: Infinity }; // REP
  this.rules[6].opcodes[3] = { type: 2, children: [4, 5, 6, 7] }; // CAT
  this.rules[6].opcodes[4] = { type: 4, index: 31 }; // RNM(S)
  this.rules[6].opcodes[5] = { type: 7, string: [43] }; // TLS
  this.rules[6].opcodes[6] = { type: 4, index: 31 }; // RNM(S)
  this.rules[6].opcodes[7] = { type: 4, index: 4 }; // RNM(string1e)

  /* number */
  this.rules[7].opcodes = [];
  this.rules[7].opcodes[0] = { type: 2, children: [1, 8] }; // CAT
  this.rules[7].opcodes[1] = { type: 1, children: [2, 3, 4, 5, 6, 7] }; // ALT
  this.rules[7].opcodes[2] = { type: 4, index: 10 }; // RNM(hexfloat)
  this.rules[7].opcodes[3] = { type: 4, index: 11 }; // RNM(hexint)
  this.rules[7].opcodes[4] = { type: 4, index: 12 }; // RNM(octint)
  this.rules[7].opcodes[5] = { type: 4, index: 13 }; // RNM(binint)
  this.rules[7].opcodes[6] = { type: 4, index: 9 }; // RNM(decnumber)
  this.rules[7].opcodes[7] = { type: 4, index: 14 }; // RNM(nonfin)
  this.rules[7].opcodes[8] = { type: 4, index: 36 }; // RNM(spec)

  /* sign */
  this.rules[8].opcodes = [];
  this.rules[8].opcodes[0] = { type: 1, children: [1, 2] }; // ALT
  this.rules[8].opcodes[1] = { type: 7, string: [43] }; // TLS
  this.rules[8].opcodes[2] = { type: 7, string: [45] }; // TLS

  /* decnumber */
  this.rules[9].opcodes = [];
  this.rules[9].opcodes[0] = { type: 2, children: [1, 3, 16] }; // CAT
  this.rules[9].opcodes[1] = { type: 3, min: 0, max: 1 }; // REP
  this.rules[9].opcodes[2] = { type: 4, index: 8 }; // RNM(sign)
  this.rules[9].opcodes[3] = { type: 1, children: [4, 12] }; // ALT
  this.rules[9].opcodes[4] = { type: 2, children: [5, 7] }; // CAT
  this.rules[9].opcodes[5] = { type: 3, min: 1, max: Infinity }; // REP
  this.rules[9].opcodes[6] = { type: 4, index: 49 }; // RNM(DIGIT)
  this.rules[9].opcodes[7] = { type: 3, min: 0, max: 1 }; // REP
  this.rules[9].opcodes[8] = { type: 2, children: [9, 10] }; // CAT
  this.rules[9].opcodes[9] = { type: 7, string: [46] }; // TLS
  this.rules[9].opcodes[10] = { type: 3, min: 0, max: Infinity }; // REP
  this.rules[9].opcodes[11] = { type: 4, index: 49 }; // RNM(DIGIT)
  this.rules[9].opcodes[12] = { type: 2, children: [13, 14] }; // CAT
  this.rules[9].opcodes[13] = { type: 7, string: [46] }; // TLS
  this.rules[9].opcodes[14] = { type: 3, min: 1, max: Infinity }; // REP
  this.rules[9].opcodes[15] = { type: 4, index: 49 }; // RNM(DIGIT)
  this.rules[9].opcodes[16] = { type: 3, min: 0, max: 1 }; // REP
  this.rules[9].opcodes[17] = { type: 2, children: [18, 19, 21] }; // CAT
  this.rules[9].opcodes[18] = { type: 7, string: [101] }; // TLS
  this.rules[9].opcodes[19] = { type: 3, min: 0, max: 1 }; // REP
  this.rules[9].opcodes[20] = { type: 4, index: 8 }; // RNM(sign)
  this.rules[9].opcodes[21] = { type: 3, min: 1, max: Infinity }; // REP
  this.rules[9].opcodes[22] = { type: 4, index: 49 }; // RNM(DIGIT)

  /* hexfloat */
  this.rules[10].opcodes = [];
  this.rules[10].opcodes[0] = { type: 2, children: [1, 3, 4, 17, 18, 20] }; // CAT
  this.rules[10].opcodes[1] = { type: 3, min: 0, max: 1 }; // REP
  this.rules[10].opcodes[2] = { type: 4, index: 8 }; // RNM(sign)
  this.rules[10].opcodes[3] = { type: 7, string: [48, 120] }; // TLS
  this.rules[10].opcodes[4] = { type: 1, children: [5, 13] }; // ALT
  this.rules[10].opcodes[5] = { type: 2, children: [6, 8] }; // CAT
  this.rules[10].opcodes[6] = { type: 3, min: 1, max: Infinity }; // REP
  this.rules[10].opcodes[7] = { type: 4, index: 53 }; // RNM(HEXDIG)
  this.rules[10].opcodes[8] = { type: 3, min: 0, max: 1 }; // REP
  this.rules[10].opcodes[9] = { type: 2, children: [10, 11] }; // CAT
  this.rules[10].opcodes[10] = { type: 7, string: [46] }; // TLS
  this.rules[10].opcodes[11] = { type: 3, min: 0, max: Infinity }; // REP
  this.rules[10].opcodes[12] = { type: 4, index: 53 }; // RNM(HEXDIG)
  this.rules[10].opcodes[13] = { type: 2, children: [14, 15] }; // CAT
  this.rules[10].opcodes[14] = { type: 7, string: [46] }; // TLS
  this.rules[10].opcodes[15] = { type: 3, min: 1, max: Infinity }; // REP
  this.rules[10].opcodes[16] = { type: 4, index: 53 }; // RNM(HEXDIG)
  this.rules[10].opcodes[17] = { type: 7, string: [112] }; // TLS
  this.rules[10].opcodes[18] = { type: 3, min: 0, max: 1 }; // REP
  this.rules[10].opcodes[19] = { type: 4, index: 8 }; // RNM(sign)
  this.rules[10].opcodes[20] = { type: 3, min: 1, max: Infinity }; // REP
  this.rules[10].opcodes[21] = { type: 4, index: 49 }; // RNM(DIGIT)

  /* hexint */
  this.rules[11].opcodes = [];
  this.rules[11].opcodes[0] = { type: 2, children: [1, 3, 4] }; // CAT
  this.rules[11].opcodes[1] = { type: 3, min: 0, max: 1 }; // REP
  this.rules[11].opcodes[2] = { type: 4, index: 8 }; // RNM(sign)
  this.rules[11].opcodes[3] = { type: 7, string: [48, 120] }; // TLS
  this.rules[11].opcodes[4] = { type: 3, min: 1, max: Infinity }; // REP
  this.rules[11].opcodes[5] = { type: 4, index: 53 }; // RNM(HEXDIG)

  /* octint */
  this.rules[12].opcodes = [];
  this.rules[12].opcodes[0] = { type: 2, children: [1, 3, 4] }; // CAT
  this.rules[12].opcodes[1] = { type: 3, min: 0, max: 1 }; // REP
  this.rules[12].opcodes[2] = { type: 4, index: 8 }; // RNM(sign)
  this.rules[12].opcodes[3] = { type: 7, string: [48, 111] }; // TLS
  this.rules[12].opcodes[4] = { type: 3, min: 1, max: Infinity }; // REP
  this.rules[12].opcodes[5] = { type: 4, index: 51 }; // RNM(ODIGIT)

  /* binint */
  this.rules[13].opcodes = [];
  this.rules[13].opcodes[0] = { type: 2, children: [1, 3, 4] }; // CAT
  this.rules[13].opcodes[1] = { type: 3, min: 0, max: 1 }; // REP
  this.rules[13].opcodes[2] = { type: 4, index: 8 }; // RNM(sign)
  this.rules[13].opcodes[3] = { type: 7, string: [48, 98] }; // TLS
  this.rules[13].opcodes[4] = { type: 3, min: 1, max: Infinity }; // REP
  this.rules[13].opcodes[5] = { type: 4, index: 52 }; // RNM(BDIGIT)

  /* nonfin */
  this.rules[14].opcodes = [];
  this.rules[14].opcodes[0] = { type: 1, children: [1, 2, 3] }; // ALT
  this.rules[14].opcodes[1] = {
    type: 6,
    string: [73, 110, 102, 105, 110, 105, 116, 121],
  }; // TBS
  this.rules[14].opcodes[2] = {
    type: 6,
    string: [45, 73, 110, 102, 105, 110, 105, 116, 121],
  }; // TBS
  this.rules[14].opcodes[3] = { type: 6, string: [78, 97, 78] }; // TBS

  /* simple */
  this.rules[15].opcodes = [];
  this.rules[15].opcodes[0] = { type: 1, children: [1, 2, 3, 4, 5] }; // ALT
  this.rules[15].opcodes[1] = { type: 6, string: [102, 97, 108, 115, 101] }; // TBS
  this.rules[15].opcodes[2] = { type: 6, string: [116, 114, 117, 101] }; // TBS
  this.rules[15].opcodes[3] = { type: 6, string: [110, 117, 108, 108] }; // TBS
  this.rules[15].opcodes[4] = {
    type: 6,
    string: [117, 110, 100, 101, 102, 105, 110, 101, 100],
  }; // TBS
  this.rules[15].opcodes[5] = { type: 2, children: [6, 7, 8, 9, 10] }; // CAT
  this.rules[15].opcodes[6] = {
    type: 6,
    string: [115, 105, 109, 112, 108, 101, 40],
  }; // TBS
  this.rules[15].opcodes[7] = { type: 4, index: 31 }; // RNM(S)
  this.rules[15].opcodes[8] = { type: 4, index: 2 }; // RNM(item)
  this.rules[15].opcodes[9] = { type: 4, index: 31 }; // RNM(S)
  this.rules[15].opcodes[10] = { type: 7, string: [41] }; // TLS

  /* uint */
  this.rules[16].opcodes = [];
  this.rules[16].opcodes[0] = { type: 1, children: [1, 2] }; // ALT
  this.rules[16].opcodes[1] = { type: 7, string: [48] }; // TLS
  this.rules[16].opcodes[2] = { type: 2, children: [3, 4] }; // CAT
  this.rules[16].opcodes[3] = { type: 4, index: 50 }; // RNM(DIGIT1)
  this.rules[16].opcodes[4] = { type: 3, min: 0, max: Infinity }; // REP
  this.rules[16].opcodes[5] = { type: 4, index: 49 }; // RNM(DIGIT)

  /* tagged */
  this.rules[17].opcodes = [];
  this.rules[17].opcodes[0] = { type: 2, children: [1, 2, 3, 4, 5, 6, 7] }; // CAT
  this.rules[17].opcodes[1] = { type: 4, index: 16 }; // RNM(uint)
  this.rules[17].opcodes[2] = { type: 4, index: 36 }; // RNM(spec)
  this.rules[17].opcodes[3] = { type: 7, string: [40] }; // TLS
  this.rules[17].opcodes[4] = { type: 4, index: 31 }; // RNM(S)
  this.rules[17].opcodes[5] = { type: 4, index: 2 }; // RNM(item)
  this.rules[17].opcodes[6] = { type: 4, index: 31 }; // RNM(S)
  this.rules[17].opcodes[7] = { type: 7, string: [41] }; // TLS

  /* app-prefix */
  this.rules[18].opcodes = [];
  this.rules[18].opcodes[0] = { type: 1, children: [1, 5] }; // ALT
  this.rules[18].opcodes[1] = { type: 2, children: [2, 3] }; // CAT
  this.rules[18].opcodes[2] = { type: 4, index: 55 }; // RNM(lcalpha)
  this.rules[18].opcodes[3] = { type: 3, min: 0, max: Infinity }; // REP
  this.rules[18].opcodes[4] = { type: 4, index: 56 }; // RNM(lcalnum)
  this.rules[18].opcodes[5] = { type: 2, children: [6, 7] }; // CAT
  this.rules[18].opcodes[6] = { type: 4, index: 57 }; // RNM(ucalpha)
  this.rules[18].opcodes[7] = { type: 3, min: 0, max: Infinity }; // REP
  this.rules[18].opcodes[8] = { type: 4, index: 58 }; // RNM(ucalnum)

  /* app-string */
  this.rules[19].opcodes = [];
  this.rules[19].opcodes[0] = { type: 2, children: [1, 2] }; // CAT
  this.rules[19].opcodes[1] = { type: 4, index: 18 }; // RNM(app-prefix)
  this.rules[19].opcodes[2] = { type: 4, index: 20 }; // RNM(sqstr)

  /* sqstr */
  this.rules[20].opcodes = [];
  this.rules[20].opcodes[0] = { type: 2, children: [1, 2, 4] }; // CAT
  this.rules[20].opcodes[1] = { type: 4, index: 48 }; // RNM(SQUOTE)
  this.rules[20].opcodes[2] = { type: 3, min: 0, max: Infinity }; // REP
  this.rules[20].opcodes[3] = { type: 4, index: 39 }; // RNM(single-quoted)
  this.rules[20].opcodes[4] = { type: 4, index: 48 }; // RNM(SQUOTE)

  /* bstr */
  this.rules[21].opcodes = [];
  this.rules[21].opcodes[0] = { type: 1, children: [1, 2, 3] }; // ALT
  this.rules[21].opcodes[1] = { type: 4, index: 19 }; // RNM(app-string)
  this.rules[21].opcodes[2] = { type: 4, index: 20 }; // RNM(sqstr)
  this.rules[21].opcodes[3] = { type: 4, index: 23 }; // RNM(embedded)

  /* tstr */
  this.rules[22].opcodes = [];
  this.rules[22].opcodes[0] = { type: 2, children: [1, 2, 4] }; // CAT
  this.rules[22].opcodes[1] = { type: 4, index: 47 }; // RNM(DQUOTE)
  this.rules[22].opcodes[2] = { type: 3, min: 0, max: Infinity }; // REP
  this.rules[22].opcodes[3] = { type: 4, index: 38 }; // RNM(double-quoted)
  this.rules[22].opcodes[4] = { type: 4, index: 47 }; // RNM(DQUOTE)

  /* embedded */
  this.rules[23].opcodes = [];
  this.rules[23].opcodes[0] = { type: 2, children: [1, 2, 3] }; // CAT
  this.rules[23].opcodes[1] = { type: 7, string: [60, 60] }; // TLS
  this.rules[23].opcodes[2] = { type: 4, index: 0 }; // RNM(seq)
  this.rules[23].opcodes[3] = { type: 7, string: [62, 62] }; // TLS

  /* array */
  this.rules[24].opcodes = [];
  this.rules[24].opcodes[0] = { type: 2, children: [1, 2, 15] }; // CAT
  this.rules[24].opcodes[1] = { type: 7, string: [91] }; // TLS
  this.rules[24].opcodes[2] = { type: 1, children: [3, 12] }; // ALT
  this.rules[24].opcodes[3] = { type: 2, children: [4, 5, 6, 7, 11] }; // CAT
  this.rules[24].opcodes[4] = { type: 4, index: 37 }; // RNM(specms)
  this.rules[24].opcodes[5] = { type: 4, index: 31 }; // RNM(S)
  this.rules[24].opcodes[6] = { type: 4, index: 2 }; // RNM(item)
  this.rules[24].opcodes[7] = { type: 3, min: 0, max: Infinity }; // REP
  this.rules[24].opcodes[8] = { type: 2, children: [9, 10] }; // CAT
  this.rules[24].opcodes[9] = { type: 4, index: 33 }; // RNM(MSC)
  this.rules[24].opcodes[10] = { type: 4, index: 2 }; // RNM(item)
  this.rules[24].opcodes[11] = { type: 4, index: 34 }; // RNM(SOC)
  this.rules[24].opcodes[12] = { type: 2, children: [13, 14] }; // CAT
  this.rules[24].opcodes[13] = { type: 4, index: 36 }; // RNM(spec)
  this.rules[24].opcodes[14] = { type: 4, index: 31 }; // RNM(S)
  this.rules[24].opcodes[15] = { type: 7, string: [93] }; // TLS

  /* map */
  this.rules[25].opcodes = [];
  this.rules[25].opcodes[0] = { type: 2, children: [1, 2, 15] }; // CAT
  this.rules[25].opcodes[1] = { type: 7, string: [123] }; // TLS
  this.rules[25].opcodes[2] = { type: 1, children: [3, 12] }; // ALT
  this.rules[25].opcodes[3] = { type: 2, children: [4, 5, 6, 7, 11] }; // CAT
  this.rules[25].opcodes[4] = { type: 4, index: 37 }; // RNM(specms)
  this.rules[25].opcodes[5] = { type: 4, index: 31 }; // RNM(S)
  this.rules[25].opcodes[6] = { type: 4, index: 26 }; // RNM(keyp)
  this.rules[25].opcodes[7] = { type: 3, min: 0, max: Infinity }; // REP
  this.rules[25].opcodes[8] = { type: 2, children: [9, 10] }; // CAT
  this.rules[25].opcodes[9] = { type: 4, index: 33 }; // RNM(MSC)
  this.rules[25].opcodes[10] = { type: 4, index: 26 }; // RNM(keyp)
  this.rules[25].opcodes[11] = { type: 4, index: 34 }; // RNM(SOC)
  this.rules[25].opcodes[12] = { type: 2, children: [13, 14] }; // CAT
  this.rules[25].opcodes[13] = { type: 4, index: 36 }; // RNM(spec)
  this.rules[25].opcodes[14] = { type: 4, index: 31 }; // RNM(S)
  this.rules[25].opcodes[15] = { type: 7, string: [125] }; // TLS

  /* keyp */
  this.rules[26].opcodes = [];
  this.rules[26].opcodes[0] = { type: 2, children: [1, 2, 3, 4, 5] }; // CAT
  this.rules[26].opcodes[1] = { type: 4, index: 2 }; // RNM(item)
  this.rules[26].opcodes[2] = { type: 4, index: 31 }; // RNM(S)
  this.rules[26].opcodes[3] = { type: 7, string: [58] }; // TLS
  this.rules[26].opcodes[4] = { type: 4, index: 31 }; // RNM(S)
  this.rules[26].opcodes[5] = { type: 4, index: 2 }; // RNM(item)

  /* blank */
  this.rules[27].opcodes = [];
  this.rules[27].opcodes[0] = { type: 1, children: [1, 2, 3, 4] }; // ALT
  this.rules[27].opcodes[1] = { type: 6, string: [9] }; // TBS
  this.rules[27].opcodes[2] = { type: 6, string: [10] }; // TBS
  this.rules[27].opcodes[3] = { type: 6, string: [13] }; // TBS
  this.rules[27].opcodes[4] = { type: 6, string: [32] }; // TBS

  /* non-slash */
  this.rules[28].opcodes = [];
  this.rules[28].opcodes[0] = { type: 1, children: [1, 2, 3, 4] }; // ALT
  this.rules[28].opcodes[1] = { type: 4, index: 27 }; // RNM(blank)
  this.rules[28].opcodes[2] = { type: 5, min: 33, max: 46 }; // TRG
  this.rules[28].opcodes[3] = { type: 5, min: 48, max: 55295 }; // TRG
  this.rules[28].opcodes[4] = { type: 5, min: 57344, max: 1114111 }; // TRG

  /* non-lf */
  this.rules[29].opcodes = [];
  this.rules[29].opcodes[0] = { type: 1, children: [1, 2, 3, 4] }; // ALT
  this.rules[29].opcodes[1] = { type: 6, string: [9] }; // TBS
  this.rules[29].opcodes[2] = { type: 6, string: [13] }; // TBS
  this.rules[29].opcodes[3] = { type: 5, min: 32, max: 55295 }; // TRG
  this.rules[29].opcodes[4] = { type: 5, min: 57344, max: 1114111 }; // TRG

  /* comment */
  this.rules[30].opcodes = [];
  this.rules[30].opcodes[0] = { type: 1, children: [1, 6] }; // ALT
  this.rules[30].opcodes[1] = { type: 2, children: [2, 3, 5] }; // CAT
  this.rules[30].opcodes[2] = { type: 7, string: [47] }; // TLS
  this.rules[30].opcodes[3] = { type: 3, min: 0, max: Infinity }; // REP
  this.rules[30].opcodes[4] = { type: 4, index: 28 }; // RNM(non-slash)
  this.rules[30].opcodes[5] = { type: 7, string: [47] }; // TLS
  this.rules[30].opcodes[6] = { type: 2, children: [7, 8, 10] }; // CAT
  this.rules[30].opcodes[7] = { type: 7, string: [35] }; // TLS
  this.rules[30].opcodes[8] = { type: 3, min: 0, max: Infinity }; // REP
  this.rules[30].opcodes[9] = { type: 4, index: 29 }; // RNM(non-lf)
  this.rules[30].opcodes[10] = { type: 6, string: [10] }; // TBS

  /* S */
  this.rules[31].opcodes = [];
  this.rules[31].opcodes[0] = { type: 2, children: [1, 3] }; // CAT
  this.rules[31].opcodes[1] = { type: 3, min: 0, max: Infinity }; // REP
  this.rules[31].opcodes[2] = { type: 4, index: 27 }; // RNM(blank)
  this.rules[31].opcodes[3] = { type: 3, min: 0, max: Infinity }; // REP
  this.rules[31].opcodes[4] = { type: 2, children: [5, 6] }; // CAT
  this.rules[31].opcodes[5] = { type: 4, index: 30 }; // RNM(comment)
  this.rules[31].opcodes[6] = { type: 3, min: 0, max: Infinity }; // REP
  this.rules[31].opcodes[7] = { type: 4, index: 27 }; // RNM(blank)

  /* MS */
  this.rules[32].opcodes = [];
  this.rules[32].opcodes[0] = { type: 2, children: [1, 4] }; // CAT
  this.rules[32].opcodes[1] = { type: 1, children: [2, 3] }; // ALT
  this.rules[32].opcodes[2] = { type: 4, index: 27 }; // RNM(blank)
  this.rules[32].opcodes[3] = { type: 4, index: 30 }; // RNM(comment)
  this.rules[32].opcodes[4] = { type: 4, index: 31 }; // RNM(S)

  /* MSC */
  this.rules[33].opcodes = [];
  this.rules[33].opcodes[0] = { type: 1, children: [1, 4] }; // ALT
  this.rules[33].opcodes[1] = { type: 2, children: [2, 3] }; // CAT
  this.rules[33].opcodes[2] = { type: 7, string: [44] }; // TLS
  this.rules[33].opcodes[3] = { type: 4, index: 31 }; // RNM(S)
  this.rules[33].opcodes[4] = { type: 2, children: [5, 6] }; // CAT
  this.rules[33].opcodes[5] = { type: 4, index: 32 }; // RNM(MS)
  this.rules[33].opcodes[6] = { type: 3, min: 0, max: 1 }; // REP
  this.rules[33].opcodes[7] = { type: 2, children: [8, 9] }; // CAT
  this.rules[33].opcodes[8] = { type: 7, string: [44] }; // TLS
  this.rules[33].opcodes[9] = { type: 4, index: 31 }; // RNM(S)

  /* SOC */
  this.rules[34].opcodes = [];
  this.rules[34].opcodes[0] = { type: 2, children: [1, 2] }; // CAT
  this.rules[34].opcodes[1] = { type: 4, index: 31 }; // RNM(S)
  this.rules[34].opcodes[2] = { type: 3, min: 0, max: 1 }; // REP
  this.rules[34].opcodes[3] = { type: 2, children: [4, 5] }; // CAT
  this.rules[34].opcodes[4] = { type: 7, string: [44] }; // TLS
  this.rules[34].opcodes[5] = { type: 4, index: 31 }; // RNM(S)

  /* streamstring */
  this.rules[35].opcodes = [];
  this.rules[35].opcodes[0] = { type: 2, children: [1, 2, 3, 4, 8, 9] }; // CAT
  this.rules[35].opcodes[1] = { type: 7, string: [40, 95] }; // TLS
  this.rules[35].opcodes[2] = { type: 4, index: 32 }; // RNM(MS)
  this.rules[35].opcodes[3] = { type: 4, index: 6 }; // RNM(string)
  this.rules[35].opcodes[4] = { type: 3, min: 0, max: Infinity }; // REP
  this.rules[35].opcodes[5] = { type: 2, children: [6, 7] }; // CAT
  this.rules[35].opcodes[6] = { type: 4, index: 33 }; // RNM(MSC)
  this.rules[35].opcodes[7] = { type: 4, index: 6 }; // RNM(string)
  this.rules[35].opcodes[8] = { type: 4, index: 34 }; // RNM(SOC)
  this.rules[35].opcodes[9] = { type: 7, string: [41] }; // TLS

  /* spec */
  this.rules[36].opcodes = [];
  this.rules[36].opcodes[0] = { type: 3, min: 0, max: 1 }; // REP
  this.rules[36].opcodes[1] = { type: 2, children: [2, 3] }; // CAT
  this.rules[36].opcodes[2] = { type: 7, string: [95] }; // TLS
  this.rules[36].opcodes[3] = { type: 3, min: 0, max: Infinity }; // REP
  this.rules[36].opcodes[4] = { type: 4, index: 59 }; // RNM(wordchar)

  /* specms */
  this.rules[37].opcodes = [];
  this.rules[37].opcodes[0] = { type: 3, min: 0, max: 1 }; // REP
  this.rules[37].opcodes[1] = { type: 2, children: [2, 3, 5] }; // CAT
  this.rules[37].opcodes[2] = { type: 7, string: [95] }; // TLS
  this.rules[37].opcodes[3] = { type: 3, min: 0, max: Infinity }; // REP
  this.rules[37].opcodes[4] = { type: 4, index: 59 }; // RNM(wordchar)
  this.rules[37].opcodes[5] = { type: 4, index: 32 }; // RNM(MS)

  /* double-quoted */
  this.rules[38].opcodes = [];
  this.rules[38].opcodes[0] = { type: 1, children: [1, 2, 3, 6] }; // ALT
  this.rules[38].opcodes[1] = { type: 4, index: 46 }; // RNM(unescaped)
  this.rules[38].opcodes[2] = { type: 4, index: 48 }; // RNM(SQUOTE)
  this.rules[38].opcodes[3] = { type: 2, children: [4, 5] }; // CAT
  this.rules[38].opcodes[4] = { type: 7, string: [92] }; // TLS
  this.rules[38].opcodes[5] = { type: 4, index: 47 }; // RNM(DQUOTE)
  this.rules[38].opcodes[6] = { type: 2, children: [7, 8] }; // CAT
  this.rules[38].opcodes[7] = { type: 7, string: [92] }; // TLS
  this.rules[38].opcodes[8] = { type: 4, index: 40 }; // RNM(escapable)

  /* single-quoted */
  this.rules[39].opcodes = [];
  this.rules[39].opcodes[0] = { type: 1, children: [1, 2, 3, 6] }; // ALT
  this.rules[39].opcodes[1] = { type: 4, index: 46 }; // RNM(unescaped)
  this.rules[39].opcodes[2] = { type: 4, index: 47 }; // RNM(DQUOTE)
  this.rules[39].opcodes[3] = { type: 2, children: [4, 5] }; // CAT
  this.rules[39].opcodes[4] = { type: 7, string: [92] }; // TLS
  this.rules[39].opcodes[5] = { type: 4, index: 48 }; // RNM(SQUOTE)
  this.rules[39].opcodes[6] = { type: 2, children: [7, 8] }; // CAT
  this.rules[39].opcodes[7] = { type: 7, string: [92] }; // TLS
  this.rules[39].opcodes[8] = { type: 4, index: 40 }; // RNM(escapable)

  /* escapable */
  this.rules[40].opcodes = [];
  this.rules[40].opcodes[0] = { type: 1, children: [1, 2, 3, 4, 5, 6, 7, 8] }; // ALT
  this.rules[40].opcodes[1] = { type: 6, string: [98] }; // TBS
  this.rules[40].opcodes[2] = { type: 6, string: [102] }; // TBS
  this.rules[40].opcodes[3] = { type: 6, string: [110] }; // TBS
  this.rules[40].opcodes[4] = { type: 6, string: [114] }; // TBS
  this.rules[40].opcodes[5] = { type: 6, string: [116] }; // TBS
  this.rules[40].opcodes[6] = { type: 7, string: [47] }; // TLS
  this.rules[40].opcodes[7] = { type: 7, string: [92] }; // TLS
  this.rules[40].opcodes[8] = { type: 2, children: [9, 10] }; // CAT
  this.rules[40].opcodes[9] = { type: 6, string: [117] }; // TBS
  this.rules[40].opcodes[10] = { type: 4, index: 41 }; // RNM(hexchar)

  /* hexchar */
  this.rules[41].opcodes = [];
  this.rules[41].opcodes[0] = { type: 1, children: [1, 11, 12] }; // ALT
  this.rules[41].opcodes[1] = { type: 2, children: [2, 3, 10] }; // CAT
  this.rules[41].opcodes[2] = { type: 7, string: [123] }; // TLS
  this.rules[41].opcodes[3] = { type: 1, children: [4, 9] }; // ALT
  this.rules[41].opcodes[4] = { type: 2, children: [5, 7] }; // CAT
  this.rules[41].opcodes[5] = { type: 3, min: 1, max: Infinity }; // REP
  this.rules[41].opcodes[6] = { type: 7, string: [48] }; // TLS
  this.rules[41].opcodes[7] = { type: 3, min: 0, max: 1 }; // REP
  this.rules[41].opcodes[8] = { type: 4, index: 45 }; // RNM(hexscalar)
  this.rules[41].opcodes[9] = { type: 4, index: 45 }; // RNM(hexscalar)
  this.rules[41].opcodes[10] = { type: 7, string: [125] }; // TLS
  this.rules[41].opcodes[11] = { type: 4, index: 42 }; // RNM(non-surrogate)
  this.rules[41].opcodes[12] = { type: 2, children: [13, 14, 15, 16] }; // CAT
  this.rules[41].opcodes[13] = { type: 4, index: 43 }; // RNM(high-surrogate)
  this.rules[41].opcodes[14] = { type: 7, string: [92] }; // TLS
  this.rules[41].opcodes[15] = { type: 6, string: [117] }; // TBS
  this.rules[41].opcodes[16] = { type: 4, index: 44 }; // RNM(low-surrogate)

  /* non-surrogate */
  this.rules[42].opcodes = [];
  this.rules[42].opcodes[0] = { type: 1, children: [1, 11] }; // ALT
  this.rules[42].opcodes[1] = { type: 2, children: [2, 9] }; // CAT
  this.rules[42].opcodes[2] = { type: 1, children: [3, 4, 5, 6, 7, 8] }; // ALT
  this.rules[42].opcodes[3] = { type: 4, index: 49 }; // RNM(DIGIT)
  this.rules[42].opcodes[4] = { type: 7, string: [97] }; // TLS
  this.rules[42].opcodes[5] = { type: 7, string: [98] }; // TLS
  this.rules[42].opcodes[6] = { type: 7, string: [99] }; // TLS
  this.rules[42].opcodes[7] = { type: 7, string: [101] }; // TLS
  this.rules[42].opcodes[8] = { type: 7, string: [102] }; // TLS
  this.rules[42].opcodes[9] = { type: 3, min: 3, max: 3 }; // REP
  this.rules[42].opcodes[10] = { type: 4, index: 53 }; // RNM(HEXDIG)
  this.rules[42].opcodes[11] = { type: 2, children: [12, 13, 14] }; // CAT
  this.rules[42].opcodes[12] = { type: 7, string: [100] }; // TLS
  this.rules[42].opcodes[13] = { type: 4, index: 51 }; // RNM(ODIGIT)
  this.rules[42].opcodes[14] = { type: 3, min: 2, max: 2 }; // REP
  this.rules[42].opcodes[15] = { type: 4, index: 53 }; // RNM(HEXDIG)

  /* high-surrogate */
  this.rules[43].opcodes = [];
  this.rules[43].opcodes[0] = { type: 2, children: [1, 2, 7] }; // CAT
  this.rules[43].opcodes[1] = { type: 7, string: [100] }; // TLS
  this.rules[43].opcodes[2] = { type: 1, children: [3, 4, 5, 6] }; // ALT
  this.rules[43].opcodes[3] = { type: 7, string: [56] }; // TLS
  this.rules[43].opcodes[4] = { type: 7, string: [57] }; // TLS
  this.rules[43].opcodes[5] = { type: 7, string: [97] }; // TLS
  this.rules[43].opcodes[6] = { type: 7, string: [98] }; // TLS
  this.rules[43].opcodes[7] = { type: 3, min: 2, max: 2 }; // REP
  this.rules[43].opcodes[8] = { type: 4, index: 53 }; // RNM(HEXDIG)

  /* low-surrogate */
  this.rules[44].opcodes = [];
  this.rules[44].opcodes[0] = { type: 2, children: [1, 2, 7] }; // CAT
  this.rules[44].opcodes[1] = { type: 7, string: [100] }; // TLS
  this.rules[44].opcodes[2] = { type: 1, children: [3, 4, 5, 6] }; // ALT
  this.rules[44].opcodes[3] = { type: 7, string: [99] }; // TLS
  this.rules[44].opcodes[4] = { type: 7, string: [100] }; // TLS
  this.rules[44].opcodes[5] = { type: 7, string: [101] }; // TLS
  this.rules[44].opcodes[6] = { type: 7, string: [102] }; // TLS
  this.rules[44].opcodes[7] = { type: 3, min: 2, max: 2 }; // REP
  this.rules[44].opcodes[8] = { type: 4, index: 53 }; // RNM(HEXDIG)

  /* hexscalar */
  this.rules[45].opcodes = [];
  this.rules[45].opcodes[0] = { type: 1, children: [1, 5, 9, 10] }; // ALT
  this.rules[45].opcodes[1] = { type: 2, children: [2, 3] }; // CAT
  this.rules[45].opcodes[2] = { type: 7, string: [49, 48] }; // TLS
  this.rules[45].opcodes[3] = { type: 3, min: 4, max: 4 }; // REP
  this.rules[45].opcodes[4] = { type: 4, index: 53 }; // RNM(HEXDIG)
  this.rules[45].opcodes[5] = { type: 2, children: [6, 7] }; // CAT
  this.rules[45].opcodes[6] = { type: 4, index: 54 }; // RNM(HEXDIG1)
  this.rules[45].opcodes[7] = { type: 3, min: 4, max: 4 }; // REP
  this.rules[45].opcodes[8] = { type: 4, index: 53 }; // RNM(HEXDIG)
  this.rules[45].opcodes[9] = { type: 4, index: 42 }; // RNM(non-surrogate)
  this.rules[45].opcodes[10] = { type: 3, min: 1, max: 3 }; // REP
  this.rules[45].opcodes[11] = { type: 4, index: 53 }; // RNM(HEXDIG)

  /* unescaped */
  this.rules[46].opcodes = [];
  this.rules[46].opcodes[0] = { type: 1, children: [1, 2, 3, 4, 5, 6, 7] }; // ALT
  this.rules[46].opcodes[1] = { type: 6, string: [10] }; // TBS
  this.rules[46].opcodes[2] = { type: 6, string: [13] }; // TBS
  this.rules[46].opcodes[3] = { type: 5, min: 32, max: 33 }; // TRG
  this.rules[46].opcodes[4] = { type: 5, min: 35, max: 38 }; // TRG
  this.rules[46].opcodes[5] = { type: 5, min: 40, max: 91 }; // TRG
  this.rules[46].opcodes[6] = { type: 5, min: 93, max: 55295 }; // TRG
  this.rules[46].opcodes[7] = { type: 5, min: 57344, max: 1114111 }; // TRG

  /* DQUOTE */
  this.rules[47].opcodes = [];
  this.rules[47].opcodes[0] = { type: 6, string: [34] }; // TBS

  /* SQUOTE */
  this.rules[48].opcodes = [];
  this.rules[48].opcodes[0] = { type: 7, string: [39] }; // TLS

  /* DIGIT */
  this.rules[49].opcodes = [];
  this.rules[49].opcodes[0] = { type: 5, min: 48, max: 57 }; // TRG

  /* DIGIT1 */
  this.rules[50].opcodes = [];
  this.rules[50].opcodes[0] = { type: 5, min: 49, max: 57 }; // TRG

  /* ODIGIT */
  this.rules[51].opcodes = [];
  this.rules[51].opcodes[0] = { type: 5, min: 48, max: 55 }; // TRG

  /* BDIGIT */
  this.rules[52].opcodes = [];
  this.rules[52].opcodes[0] = { type: 5, min: 48, max: 49 }; // TRG

  /* HEXDIG */
  this.rules[53].opcodes = [];
  this.rules[53].opcodes[0] = { type: 1, children: [1, 2, 3, 4, 5, 6, 7] }; // ALT
  this.rules[53].opcodes[1] = { type: 4, index: 49 }; // RNM(DIGIT)
  this.rules[53].opcodes[2] = { type: 7, string: [97] }; // TLS
  this.rules[53].opcodes[3] = { type: 7, string: [98] }; // TLS
  this.rules[53].opcodes[4] = { type: 7, string: [99] }; // TLS
  this.rules[53].opcodes[5] = { type: 7, string: [100] }; // TLS
  this.rules[53].opcodes[6] = { type: 7, string: [101] }; // TLS
  this.rules[53].opcodes[7] = { type: 7, string: [102] }; // TLS

  /* HEXDIG1 */
  this.rules[54].opcodes = [];
  this.rules[54].opcodes[0] = { type: 1, children: [1, 2, 3, 4, 5, 6, 7] }; // ALT
  this.rules[54].opcodes[1] = { type: 4, index: 50 }; // RNM(DIGIT1)
  this.rules[54].opcodes[2] = { type: 7, string: [97] }; // TLS
  this.rules[54].opcodes[3] = { type: 7, string: [98] }; // TLS
  this.rules[54].opcodes[4] = { type: 7, string: [99] }; // TLS
  this.rules[54].opcodes[5] = { type: 7, string: [100] }; // TLS
  this.rules[54].opcodes[6] = { type: 7, string: [101] }; // TLS
  this.rules[54].opcodes[7] = { type: 7, string: [102] }; // TLS

  /* lcalpha */
  this.rules[55].opcodes = [];
  this.rules[55].opcodes[0] = { type: 5, min: 97, max: 122 }; // TRG

  /* lcalnum */
  this.rules[56].opcodes = [];
  this.rules[56].opcodes[0] = { type: 1, children: [1, 2] }; // ALT
  this.rules[56].opcodes[1] = { type: 4, index: 55 }; // RNM(lcalpha)
  this.rules[56].opcodes[2] = { type: 4, index: 49 }; // RNM(DIGIT)

  /* ucalpha */
  this.rules[57].opcodes = [];
  this.rules[57].opcodes[0] = { type: 5, min: 65, max: 90 }; // TRG

  /* ucalnum */
  this.rules[58].opcodes = [];
  this.rules[58].opcodes[0] = { type: 1, children: [1, 2] }; // ALT
  this.rules[58].opcodes[1] = { type: 4, index: 57 }; // RNM(ucalpha)
  this.rules[58].opcodes[2] = { type: 4, index: 49 }; // RNM(DIGIT)

  /* wordchar */
  this.rules[59].opcodes = [];
  this.rules[59].opcodes[0] = { type: 1, children: [1, 2, 3] }; // ALT
  this.rules[59].opcodes[1] = { type: 7, string: [95] }; // TLS
  this.rules[59].opcodes[2] = { type: 4, index: 56 }; // RNM(lcalnum)
  this.rules[59].opcodes[3] = { type: 4, index: 57 }; // RNM(ucalpha)

  // The `toString()` function will display the original grammar file(s) that produced these opcodes.
  this.toString = function () {
    var str = "";
    str += "seq             = S [item *(MSC item) SOC]\n";
    str += "one-item        = S item S\n";
    str += "item            = map / array / tagged\n";
    str += "                / number / simple\n";
    str += "                / string / streamstring\n";
    str += "\n";
    str += "string1         = (tstr / bstr) spec\n";
    str += "string1e        = string1 / ellipsis\n";
    str += 'ellipsis        = 3*"." ; "..." or more dots\n';
    str += 'string          = string1e *(S "+" S string1e)\n';
    str += "\n";
    str += "number          = (hexfloat / hexint / octint / binint\n";
    str += "                   / decnumber / nonfin) spec\n";
    str += 'sign            = "+" / "-"\n';
    str += 'decnumber       = [sign] (1*DIGIT ["." *DIGIT] / "." 1*DIGIT)\n';
    str += '                         ["e" [sign] 1*DIGIT]\n';
    str +=
      'hexfloat        = [sign] "0x" (1*HEXDIG ["." *HEXDIG] / "." 1*HEXDIG)\n';
    str += '                         "p" [sign] 1*DIGIT\n';
    str += 'hexint          = [sign] "0x" 1*HEXDIG\n';
    str += 'octint          = [sign] "0o" 1*ODIGIT\n';
    str += 'binint          = [sign] "0b" 1*BDIGIT\n';
    str += 'nonfin          = %s"Infinity"\n';
    str += '                / %s"-Infinity"\n';
    str += '                / %s"NaN"\n';
    str += 'simple          = %s"false"\n';
    str += '                / %s"true"\n';
    str += '                / %s"null"\n';
    str += '                / %s"undefined"\n';
    str += '                / %s"simple(" S item S ")"\n';
    str += 'uint            = "0" / DIGIT1 *DIGIT\n';
    str += 'tagged          = uint spec "(" S item S ")"\n';
    str += "\n";
    str += "app-prefix      = lcalpha *lcalnum ; including h and b64\n";
    str += "                / ucalpha *ucalnum ; tagged variant, if defined\n";
    str += "app-string      = app-prefix sqstr\n";
    str += "sqstr           = SQUOTE *single-quoted SQUOTE\n";
    str += "bstr            = app-string / sqstr / embedded\n";
    str += "                  ; app-string could be any type\n";
    str += "tstr            = DQUOTE *double-quoted DQUOTE\n";
    str += 'embedded        = "<<" seq ">>"\n';
    str += "\n";
    str +=
      'array           = "[" (specms S item *(MSC item) SOC / spec S) "]"\n';
    str +=
      'map             = "{" (specms S keyp *(MSC keyp) SOC / spec S) "}"\n';
    str += 'keyp            = item S ":" S item\n';
    str += "\n";
    str += "; We allow %x09 HT in prose, but not in strings\n";
    str += "blank           = %x09 / %x0A / %x0D / %x20\n";
    str += "non-slash       = blank / %x21-2e / %x30-D7FF / %xE000-10FFFF\n";
    str += "non-lf          = %x09 / %x0D / %x20-D7FF / %xE000-10FFFF\n";
    str += 'comment         = "/" *non-slash "/"\n';
    str += '                / "#" *non-lf %x0A\n';
    str += "; optional space\n";
    str += "S               = *blank *(comment *blank)\n";
    str += "; mandatory space\n";
    str += "MS              = (blank/comment) S\n";
    str += "; mandatory comma and/or space\n";
    str += 'MSC             = ("," S) / (MS ["," S])\n';
    str += "; optional comma and/or space\n";
    str += 'SOC             = S ["," S]\n';
    str += "\n";
    str +=
      "; check semantically that strings are either all text or all bytes\n";
    str += "; note that there must be at least one string to distinguish\n";
    str += 'streamstring    = "(_" MS string *(MSC string) SOC ")"\n';
    str += 'spec            = ["_" *wordchar]\n';
    str += 'specms          = ["_" *wordchar MS]\n';
    str += "\n";
    str += "double-quoted   = unescaped\n";
    str += "                / SQUOTE\n";
    str += '                / "\\" DQUOTE\n';
    str += '                / "\\" escapable\n';
    str += "\n";
    str += "single-quoted   = unescaped\n";
    str += "                / DQUOTE\n";
    str += '                / "\\" SQUOTE\n';
    str += '                / "\\" escapable\n';
    str += "\n";
    str += 'escapable       = %s"b" ; BS backspace U+0008\n';
    str += '                / %s"f" ; FF form feed U+000C\n';
    str += '                / %s"n" ; LF line feed U+000A\n';
    str += '                / %s"r" ; CR carriage return U+000D\n';
    str += '                / %s"t" ; HT horizontal tab U+0009\n';
    str += '                / "/"   ; / slash (solidus) U+002F (JSON!)\n';
    str += '                / "\\"   ; \\ backslash (reverse solidus) U+005C\n';
    str += '                / (%s"u" hexchar) ;  uXXXX      U+XXXX\n';
    str += "\n";
    str += 'hexchar         = "{" (1*"0" [ hexscalar ] / hexscalar) "}"\n';
    str += "                / non-surrogate\n";
    str += '                / (high-surrogate "\\" %s"u" low-surrogate)\n';
    str += 'non-surrogate   = ((DIGIT / "A"/"B"/"C" / "E"/"F") 3HEXDIG)\n';
    str += '                / ("D" ODIGIT 2HEXDIG )\n';
    str += 'high-surrogate  = "D" ("8"/"9"/"A"/"B") 2HEXDIG\n';
    str += 'low-surrogate   = "D" ("C"/"D"/"E"/"F") 2HEXDIG\n';
    str += 'hexscalar       = "10" 4HEXDIG / HEXDIG1 4HEXDIG\n';
    str += "                / non-surrogate / 1*3HEXDIG\n";
    str += "\n";
    str +=
      "; Note that no other C0 characters are allowed, including %x09 HT\n";
    str += "unescaped       = %x0A ; new line\n";
    str += "                / %x0D ; carriage return -- ignored on input\n";
    str += "                / %x20-21\n";
    str += '                     ; omit 0x22 "\n';
    str += "                / %x23-26\n";
    str += "                     ; omit 0x27 '\n";
    str += "                / %x28-5B\n";
    str += "                     ; omit 0x5C \\\n";
    str += "                / %x5D-D7FF ; skip surrogate code points\n";
    str += "                / %xE000-10FFFF\n";
    str += "\n";
    str += 'DQUOTE          = %x22    ; " double quote\n';
    str += "SQUOTE          = \"'\"     ; ' single quote\n";
    str += "DIGIT           = %x30-39 ; 0-9\n";
    str += "DIGIT1          = %x31-39 ; 1-9\n";
    str += "ODIGIT          = %x30-37 ; 0-7\n";
    str += "BDIGIT          = %x30-31 ; 0-1\n";
    str += 'HEXDIG          = DIGIT / "A" / "B" / "C" / "D" / "E" / "F"\n';
    str += 'HEXDIG1         = DIGIT1 / "A" / "B" / "C" / "D" / "E" / "F"\n';
    str +=
      '; Note: double-quoted strings as in "A" are case-insensitive in ABNF\n';
    str += "lcalpha         = %x61-7A ; a-z\n";
    str += "lcalnum         = lcalpha / DIGIT\n";
    str += "ucalpha         = %x41-5A ; A-Z\n";
    str += "ucalnum         = ucalpha / DIGIT\n";
    str += 'wordchar        = "_" / lcalnum / ucalpha ; [_a-z0-9A-Z]\n';
    return str;
  };
};
